language: rust
rust:
  - stable
  - nightly

env:
  - FLAGS=""
  - FLAGS="--features std"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libudev-dev

script: cargo test $FLAGS
