[package]
name = "dynamixel"
version = "0.0.0"
authors = ["Kjetil Kjeka <kjetilkjeka@gmail.com>"]

[dependencies]
bit_field = "0.9.0"
embedded_types = "0.3.2"
serialport = {version = "2.0", optional = true}

[features]
default = []
std = []